apiVersion: v1
kind: Service
metadata:
  name: nexus-service
  namespace: nexus-namespace
spec:
  type: LoadBalancer
  ports:
  - port: 8081
    targetPort: 8081
    nodePort: 30081
  selector:
    app: nexus
