apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus
  namespace: nexus-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexus
  template:
    metadata:
      labels:
        app: nexus
    spec:
#      affinity:  # Define affinity settings here
#        podAffinity:  # This ensures that the pods are scheduled on the same node
#          requiredDuringSchedulingIgnoredDuringExecution:
#            - labelSelector:
#                matchExpressions:
#                  - key: app
#                    operator: In
#                    values:
#                    - nexus
#              topologyKey: "kubernetes.io/192.168.1.213"
      initContainers:
      - name: fix-perms
        image: busybox
        command: ['sh', '-c', 'chown -R 200:200 /nexus-data']
        volumeMounts:
        - name: nexus-data
          mountPath: /nexus-data
      containers:
      - name: nexus
        image: sonatype/nexus3:latest
        resources:
          limits:
            memory: "2Gi"
            cpu: "4"
        requests:
            memory: "2Gi"
            cpu: "2"
        env:
          - name: INSTALL4J_ADD_VM_PARAMS
            value: "-Xms2g -Xmx2g"
        ports:
        - containerPort: 8081
        volumeMounts:
        - name: nexus-data
          mountPath: /nexus-data
      volumes:
      - name: nexus-data
        persistentVolumeClaim:
          claimName: nexus-pvc
